[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 300

[deploy.multiRegionConfig.us-west2]
numReplicas = 1

[networking]
staticOutboundIp = true