[build]
builder = "DOCKERFILE"
dockerfilePath = "golang/invest-tracker/Dockerfile.script"
[deploy]
healthcheckPath = "/debug/health"
healthcheckTimeout = 300

[deploy.multiRegionConfig.us-west2]
numReplicas = 1

[networking]
staticOutboundIp = true