version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: deploy/docker/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=invest_tracker
    depends_on:
      - mongodb
    restart: unless-stopped

  data-collector:
    build:
      context: .
      dockerfile: deploy/docker/job-collector/Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=invest_tracker
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
