basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@systentando.com.br
    name: API Support
    url: http://www.systentando.com.br/support
  description: API for tracking and analyzing investments across different asset types
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Investment Tracker API
  version: "1.0"
paths: {}
schemes:
- http
- https
swagger: "2.0"
