[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.multiRegionConfig.us-west2]
numReplicas = 1

[networking]
staticOutboundIp = true

# Configurações específicas para Go
[deploy.env]
GIN_MODE = "release"
PORT = "8080"
