[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.multiRegionConfig.us-west2]
numReplicas = 2

[networking]
staticOutboundIp = true

# Configurações específicas para Node.js
[deploy.env]
NODE_ENV = "production"
PORT = "3000"
