[build]
builder = "DOCKERFILE"
dockerfilePath = "python/Dockerfile"
context = "python"  # Adicionar esta linha

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
# Adicionar delay para healthcheck
healthcheckInterval = 30

[deploy.multiRegionConfig.us-west2]
numReplicas = 1

[networking]
staticOutboundIp = false

# Configurações específicas para Python
[deploy.env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8000"
# Adicionar variáveis de ambiente padrão
OPENAI_API_KEY = "dummy_key_for_testing"
DEBUG = "true"
