[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.multiRegionConfig.us-west2]
numReplicas = 1

[networking]
staticOutboundIp = true

# Configurações específicas para Python
[deploy.env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PORT = "8000"
